version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - cd lambda-deploy/
      - npm install -g typescript@2.9.2
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - mkdir artifacts
      - tsc
      - mv dist/index.js artifacts
      - mv node_modules artifacts
      - cd artifacts
      - zip -qr ../../aws-helpers-lambda-deploy.zip ./
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files:
      - aws-helpers-lambda-deploy.zip