version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g typescript@2.9.2
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - tsc -p lambda-deploy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
    files:
      - './dist/*'
    name: lambda-deploy